# Generated by Django 5.1.2 on 2024-10-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
