# Generated by Django 5.1.2 on 2024-10-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pdf_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
